# Dependencies
markdown:         kramdown

# Permalinks
permalink:        /:year/:month/:day/:title/

# Setup
title:            如是我聞
description:      Keep Calm and Follow the Code
url:              http://ztpala.com
domain:           ztpala.com
email:            ztpala@gmail.com
twitter_username: ztpala
github_username:  pala
timezone:         America/New_York
subscribe:        http://feed.ztpala.com
exclude:          [ README.md, newpost.rb, CNAME ]

baseurl: "" # the subpath of your site, e.g. /blog

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - newpost.rb
  - CNAME

disqus_shortname: ztpala
google_analytics_id: UA-5531632-1
